"use client"

import React, { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import {
  CheckCircle,
  Shield,
  Download,
  Share2,
  Eye,
  Copy,
  Calendar,
  Clock,
  User,
  Vote,
  Hash,
  Printer,
  QrCode,
  ExternalLink
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Separator } from "@/components/ui/separator"
import { LoadingSpinner } from "@/components/shared/LoadingSpinner"
import { getVoteReceipt } from "@/lib/api/votes"
import type { VoteReceipt as VoteReceiptType, Election, Position, Candidate } from "@/lib/types"
import { cn } from "@/lib/utils/cn"
import { format } from "date-fns"

interface VoteReceiptProps {
  receiptHash?: string
  receipt?: VoteReceiptType
  election?: Election
  className?: string
  showActions?: boolean
  variant?: "default" | "compact" | "print"
}

export function VoteReceipt({
  receiptHash,
  receipt: providedReceipt,
  election,
  className,
  showActions = true,
  variant = "default"
}: VoteReceiptProps) {
  const [isSharing, setIsSharing] = useState(false)

  // Fetch receipt if only hash is provided
  const { data: receiptData, isLoading, error } = useQuery({
    queryKey: ['vote-receipt', receiptHash],
    queryFn: () => receiptHash ? getVoteReceipt(receiptHash) : null,
    enabled: !!receiptHash && !providedReceipt,
  })

  const receipt = providedReceipt || receiptData?.data?.data

  const copyToClipboard = async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text)
      // You can add toast notification here
      console.log(`${label} copied to clipboard`)
    } catch (error) {
      console.error('Failed to copy to clipboard:', error)
    }
  }

  const handlePrint = () => {
    window.print()
  }

  const handleDownload = () => {
    if (!receipt) return

    const receiptText = generateReceiptText()
    const blob = new Blob([receiptText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `vote-receipt-${receipt.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleShare = async () => {
    if (!receipt) return

    setIsSharing(true)
    try {
      if (navigator.share) {
        await navigator.share({
          title: `Vote Receipt - ${election?.title || 'Election'}`,
          text: `I have successfully voted in ${election?.title || 'the election'}. Receipt ID: ${receipt.id}`,
          url: window.location.href
        })
      } else {
        await copyToClipboard(
          `I have successfully voted in ${election?.title || 'the election'}. Receipt ID: ${receipt.id}`,
          "Vote confirmation"
        )
      }
    } catch (error) {
      console.error('Share failed:', error)
    } finally {
      setIsSharing(false)
    }
  }

  const generateReceiptText = () => {
    if (!receipt) return ""

    return `
UNIELECT DIGITAL VOTING SYSTEM
VOTE RECEIPT

Election: ${election?.title || 'Unknown Election'}
Voter ID: ${receipt.voterId}
Receipt ID: ${receipt.id}
Verification Code: ${receipt.verificationCode}
Timestamp: ${format(new Date(receipt.timestamp), 'PPPp')}

${receipt.positions.map((position, index) => `
Position ${index + 1}: ${position.positionName || 'Unknown Position'}
${position.abstained ? 'ABSTAINED' : position.candidateNames?.join(', ') || 'No candidates selected'}
`).join('')}

Status: ${receipt.verified ? 'VALID' : 'INVALID'}
Receipt Hash: ${receipt.receiptHash || 'Processing...'}

This receipt serves as proof of your vote submission.
Keep this receipt for your records.

Generated by UniElect Voting System
`.trim()
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-96">
        <LoadingSpinner size="lg" />
        <span className="ml-4 text-lg">Loading receipt...</span>
      </div>
    )
  }

  if (error) {
    return (
      <Alert variant="destructive">
        <AlertDescription>
          Failed to load vote receipt: {(error as any)?.response?.data?.message || "Unknown error"}
        </AlertDescription>
      </Alert>
    )
  }

  if (!receipt) {
    return (
      <Alert>
        <AlertDescription>
          No vote receipt available.
        </AlertDescription>
      </Alert>
    )
  }

  if (variant === "compact") {
    return (
      <Card className={cn("border-green-200 bg-green-50/50", className)}>
        <CardContent className="p-4">
          <div className="flex items-center space-x-4">
            <div className="flex-shrink-0">
              <div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center">
                <CheckCircle className="h-6 w-6 text-green-600" />
              </div>
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="font-semibold text-green-900">Vote Submitted Successfully</h3>
              <p className="text-sm text-green-700">Receipt ID: {receipt.id}</p>
              <p className="text-xs text-green-600">
                {format(new Date(receipt.timestamp), 'PPp')}
              </p>
            </div>
            <div className="flex-shrink-0">
              <Button
                size="sm"
                variant="outline"
                onClick={() => copyToClipboard(receipt.verificationCode, "Verification code")}
              >
                <Copy className="h-3 w-3 mr-1" />
                Copy Code
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className={cn("space-y-6", className)}>
      {/* Success Header */}
      <Card className="border-green-200 bg-green-50/50">
        <CardContent className="pt-6">
          <div className="text-center">
            <div className="mx-auto w-16 h-16 rounded-full bg-green-100 flex items-center justify-center mb-4">
              <CheckCircle className="h-8 w-8 text-green-600" />
            </div>
            <h2 className="text-2xl font-bold text-green-900 mb-2">
              Vote Submitted Successfully!
            </h2>
            <p className="text-green-700 mb-4">
              Your vote has been securely recorded and verified.
            </p>
            <div className="flex items-center justify-center space-x-2">
              <Shield className="h-4 w-4 text-green-600" />
              <span className="text-sm text-green-600 font-medium">
                Protected by blockchain technology
              </span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Receipt Details */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Vote className="h-5 w-5 text-blue-600" />
            <span>Vote Receipt</span>
          </CardTitle>
          <CardDescription>
            Official proof of your vote submission. Keep this for your records.
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Receipt Metadata */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-3">
              <div>
                <label className="text-sm font-medium text-gray-700">Receipt ID</label>
                <div className="flex items-center space-x-2 mt-1">
                  <code className="text-sm bg-gray-100 px-2 py-1 rounded font-mono">
                    {receipt.id}
                  </code>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => copyToClipboard(receipt.id, "Receipt ID")}
                  >
                    <Copy className="h-3 w-3" />
                  </Button>
                </div>
              </div>

              <div>
                <label className="text-sm font-medium text-gray-700">Verification Code</label>
                <div className="flex items-center space-x-2 mt-1">
                  <code className="text-sm bg-gray-100 px-2 py-1 rounded font-mono">
                    {receipt.verificationCode}
                  </code>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => copyToClipboard(receipt.verificationCode, "Verification code")}
                  >
                    <Copy className="h-3 w-3" />
                  </Button>
                </div>
              </div>

              <div>
                <label className="text-sm font-medium text-gray-700">Election</label>
                <p className="text-sm mt-1">{election?.title || 'Unknown Election'}</p>
              </div>
            </div>

            <div className="space-y-3">
              <div>
                <label className="text-sm font-medium text-gray-700">Timestamp</label>
                <div className="flex items-center space-x-2 mt-1">
                  <Calendar className="h-4 w-4 text-gray-400" />
                  <span className="text-sm">{format(new Date(receipt.timestamp), 'PPP')}</span>
                </div>
                <div className="flex items-center space-x-2 mt-1">
                  <Clock className="h-4 w-4 text-gray-400" />
                  <span className="text-sm">{format(new Date(receipt.timestamp), 'p')}</span>
                </div>
              </div>

              <div>
                <label className="text-sm font-medium text-gray-700">Status</label>
                <div className="mt-1">
                  <Badge variant={receipt.verified ? "success" : "destructive"}>
                    {receipt.verified ? "Verified" : "Pending"}
                  </Badge>
                </div>
              </div>

              <div>
                <label className="text-sm font-medium text-gray-700">Receipt Hash</label>
                <div className="flex items-center space-x-2 mt-1">
                  <code className="text-xs bg-gray-100 px-2 py-1 rounded font-mono truncate">
                    {receipt.receiptHash}
                  </code>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => copyToClipboard(receipt.receiptHash, "Receipt hash")}
                  >
                    <Copy className="h-3 w-3" />
                  </Button>
                </div>
              </div>
            </div>
          </div>

          <Separator />

          {/* Vote Details */}
          <div className="space-y-4">
            <h3 className="font-semibold text-gray-900">Your Votes</h3>
            <div className="space-y-4">
              {receipt.positions.map((position, index: number) => (
                <div key={index} className="border rounded-lg p-4">
                  <div className="flex items-start justify-between mb-2">
                    <h4 className="font-medium text-gray-900">
                      {position.positionName || `Position ${index + 1}`}
                    </h4>
                    {position.abstained && (
                      <Badge variant="outline" className="text-amber-600">
                        Abstained
                      </Badge>
                    )}
                  </div>

                  {position.abstained ? (
                    <p className="text-sm text-gray-600">
                      You chose to abstain from voting for this position.
                    </p>
                  ) : (
                    <div className="space-y-2">
                      {position.candidateNames?.map((candidateName: string, idx: number) => (
                        <div key={idx} className="flex items-center space-x-2">
                          <CheckCircle className="h-4 w-4 text-green-600" />
                          <span className="text-sm">{candidateName}</span>
                        </div>
                      )) || (
                        <p className="text-sm text-gray-500">No candidate information available</p>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {showActions && (
            <>
              <Separator />

              {/* Actions */}
              <div className="flex flex-wrap gap-3">
                <Button onClick={handleDownload} variant="outline">
                  <Download className="h-4 w-4 mr-2" />
                  Download Receipt
                </Button>

                <Button onClick={handlePrint} variant="outline">
                  <Printer className="h-4 w-4 mr-2" />
                  Print Receipt
                </Button>

                <Button
                  onClick={handleShare}
                  variant="outline"
                  disabled={isSharing}
                >
                  {isSharing ? (
                    <LoadingSpinner size="sm" className="mr-2" />
                  ) : (
                    <Share2 className="h-4 w-4 mr-2" />
                  )}
                  Share Confirmation
                </Button>

                <Button
                  onClick={() => copyToClipboard(
                    `${window.location.origin}/verify-vote/${receipt.verificationCode}`,
                    "Verification URL"
                  )}
                  variant="outline"
                >
                  <ExternalLink className="h-4 w-4 mr-2" />
                  Copy Verification URL
                </Button>
              </div>
            </>
          )}
        </CardContent>
      </Card>

      {/* Security Notice */}
      <Alert>
        <Shield className="h-4 w-4" />
        <AlertDescription>
          <strong>Important:</strong> Save this receipt as proof of your vote submission.
          You can use the verification code to independently verify your vote was recorded correctly.
          Your vote is private and anonymous - this receipt only confirms submission, not your choices.
        </AlertDescription>
      </Alert>
    </div>
  )
}

export default VoteReceipt